add token variable to Job

diff --git a/.github/workflows/clone-data-slave.yaml b/.github/workflows/clone-data-slave.yaml
--- a/.github/workflows/clone-data-slave.yaml
+++ b/.github/workflows/clone-data-slave.yaml
@@ -20,6 +20,7 @@ jobs:
         run: ./scripts/init_deps.sh
         env:
           GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
+          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
       - name: kube prerequisites
         run: |
           mkdir -p ${HOME}/.kube
@@ -32,7 +33,24 @@ jobs:
           KUBE_USER: ${{ secrets.KUBE_SCW_USER_PROD_PAR1 }}
       - name: Check master availability (dont clone if master is not healthy)
         run: |
-          curl -s --fail https://search.prod-par2.judilibre.io/healthcheck | grep -q disponible && echo "master is available"
+#          curl -s --fail https://search.prod-par2.judilibre.io/healthcheck | grep -q disponible && echo "master is available"
+          echo "Checking health of prod par-2 ..."
+    
+           RESPONSE=$(curl -s --fail \
+                           -H "User-Agent: Judilibre-GitHub-Workflow/1.0" \
+                           -H "Accept: application/json" \
+                           --max-time 15 \
+                           https://search.prod-par2.judilibre.io/healthcheck)
+           
+           echo "Response: $RESPONSE"
+           
+           if echo "$RESPONSE" | grep -q "disponible"; then
+             echo "✅ Master (par-2) is healthy - proceeding with clone"
+           else
+             echo "❌ Healthcheck failed or blocked by Scaleway"
+             echo "Raw response was: $RESPONSE"
+             exit 1
+           fi
       - name: 🔄 Clone data ☸️
         run: |
           echo SCW_KUBE_PROJECT_NAME=judilibre-prod SCW_ZONE=fr-par-1 KUBE_NAMESPACE=judilibre-scw-prod-par1-master | tr ' ' '\n' > ENV_FILES_DST
